NAME = ft_display_file
CFLAS = -Wall -Werror -Wextra
CC = cc 
SRC = display_file.c

all : $(NAME)

$(NAME) : $(SRC)
	$(CC) $(CFLAGS) $(SRC) -o $(NAME)

clean :
	rm -f *.o

fclean : clean
	rm -f $(NAME)


.PHONY : clean fclean
